package remediation

// Finding represents a security issue that can be evaluated for remediation.
type Finding struct {
	Tool     string            `json:"tool"`
	RuleID   string            `json:"rule_id,omitempty"`
	Severity string            `json:"severity"`
	File     string            `json:"file"`
	Line     int               `json:"line,omitempty"`
	Column   int               `json:"column,omitempty"`
	Message  string            `json:"message"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// FindingSource identifies where normalized findings came from.
type FindingSource string

// FindingRequest describes the input needed to collect findings.
type FindingRequest struct {
	ProjectDir string            `json:"project_dir,omitempty"`
	Sources    []FindingSource   `json:"sources,omitempty"`
	Metadata   map[string]string `json:"metadata,omitempty"`
}

// FindingSet contains normalized findings returned by a finding provider.
type FindingSet struct {
	Provider string            `json:"provider"`
	Source   FindingSource     `json:"source,omitempty"`
	Findings []Finding         `json:"findings"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// RecommendationSource identifies where a recommendation came from.
type RecommendationSource string

// RecommendationRequest describes the input needed to resolve official recommendations.
type RecommendationRequest struct {
	Finding  Finding                `json:"finding"`
	Sources  []RecommendationSource `json:"sources,omitempty"`
	Metadata map[string]string      `json:"metadata,omitempty"`
}

// RecommendationSet contains recommendations returned by a recommendation provider.
type RecommendationSet struct {
	Provider        string               `json:"provider"`
	Source          RecommendationSource `json:"source,omitempty"`
	Recommendations []Recommendation     `json:"recommendations"`
	Metadata        map[string]string    `json:"metadata,omitempty"`
}

// AIProvider identifies an AI backend that can generate patches.
type AIProvider string

// PatchRequest describes the input needed to generate a structured patch.
type PatchRequest struct {
	Finding        Finding           `json:"finding"`
	Recommendation Recommendation    `json:"recommendation"`
	ProjectDir     string            `json:"project_dir,omitempty"`
	Files          []PatchFile       `json:"files,omitempty"`
	Metadata       map[string]string `json:"metadata,omitempty"`
}

// PatchFile contains file context used by a patch provider.
type PatchFile struct {
	Path     string `json:"path"`
	Content  string `json:"content,omitempty"`
	Language string `json:"language,omitempty"`
}

// PatchResponse contains a structured patch generated by an AI provider.
type PatchResponse struct {
	Provider string            `json:"provider"`
	Model    string            `json:"model,omitempty"`
	Patch    Patch             `json:"patch"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// Reference points to official remediation or vulnerability documentation.
type Reference struct {
	Title string `json:"title,omitempty"`
	URL   string `json:"url"`
	Type  string `json:"type,omitempty"`
}

// PackageImpact describes dependency information needed to apply a recommendation.
type PackageImpact struct {
	Name           string `json:"name,omitempty"`
	Ecosystem      string `json:"ecosystem,omitempty"`
	CurrentVersion string `json:"current_version,omitempty"`
	FixedVersion   string `json:"fixed_version,omitempty"`
	File           string `json:"file,omitempty"`
}

// RemediationStep describes an exact action required by a recommendation.
type RemediationStep struct {
	Action      string            `json:"action"`
	Target      string            `json:"target,omitempty"`
	Value       string            `json:"value,omitempty"`
	Description string            `json:"description,omitempty"`
	Metadata    map[string]string `json:"metadata,omitempty"`
}

// Recommendation describes a proposed remediation for a finding.
type Recommendation struct {
	ID            string               `json:"id,omitempty"`
	Provider      string               `json:"provider,omitempty"`
	Source        RecommendationSource `json:"source,omitempty"`
	Title         string               `json:"title"`
	Description   string               `json:"description,omitempty"`
	Risk          string               `json:"risk,omitempty"`
	Finding       Finding              `json:"finding"`
	PackageImpact *PackageImpact       `json:"package_impact,omitempty"`
	Steps         []RemediationStep    `json:"steps,omitempty"`
	Patches       []Patch              `json:"patches,omitempty"`
	References    []Reference          `json:"references,omitempty"`
	Metadata      map[string]string    `json:"metadata,omitempty"`
}

// Patch represents a file change proposed by a remediation provider.
type Patch struct {
	File        string            `json:"file"`
	StartLine   int               `json:"start_line,omitempty"`
	EndLine     int               `json:"end_line,omitempty"`
	Original    string            `json:"original,omitempty"`
	Replacement string            `json:"replacement,omitempty"`
	Metadata    map[string]string `json:"metadata,omitempty"`
}

// Result represents the outcome of a remediation attempt.
type Result struct {
	Finding        Finding         `json:"finding"`
	Recommendation *Recommendation `json:"recommendation,omitempty"`
	Status         string          `json:"status"`
	Patches        []Patch         `json:"patches,omitempty"`
	Error          error           `json:"-"`
}

// Options controls how the remediation engine is configured.
type Options struct {
	DryRun bool
}
